### PR TITLE
Fix to be able to set port to *

### PR DESCRIPTION
**Pull request by mtparet**
* Quick fix if port is equal to * 
* Add test on this case

### CODE REVIEW

**Comment by gamache** [comment]
Thanks for the patch!

**Comment by mtparet** [comment]
Thank you for merging!

**Comment by mtparet** [comment]
Hey @gamache, is it possible to get a new gem version for this fix ?

**Comment by gamache** [comment]
Sure, sorry I didn't do this earlier!  This will be released as 0.2.3.

I have recently written an Elixir port of FuzzyURL (https://github.com/gamache/fuzzyurl.ex), which has better wildcards and a more consistent interface.  I am planning to bring these changes to the Ruby gem, under version 0.5.x.  Your patch will be the last of the 0.2.x series.

**Comment by mtparet** [comment]
Thanks a lot @gamache !

**Pull request merged**
